import React, { useState } from "react";
import DunderMifflinEmployees from "./components/DunderMifflinEmployees";
import NewEmployee from "./components/NewEmployee/NewEmployee";

const INITIAL_EMPLOYEES = [
  {
    id: "e1",
    name: "Dwight Schrute",
    street: "234 Burt Ave",
    city: "Raleigh",
    state: "NC",
    zip: 27601,
    month: "January",
    day: 14,
    year: 1975,
    position: "Sales",
  },
  {
    id: "e2",
    name: "Jim Halpert",
    street: "234 Park Ave",
    city: "Raleigh",
    state: "NC",
    zip: 27604,
    month: "February",
    day: 25,
    year: 1978,
    position: "Sales",
  },
  {
    id: "e3",
    name: "Pam Beasley",
    street: "543 Lee St",
    city: "Raleigh",
    state: "NC",
    zip: 27609,
    month: "March",
    day: 5,
    year: 1985,
    position: "Reception",
  },
  {
    id: "e4",
    name: "Jan Levinson",
    street: "987 Easy St",
    city: "Raleigh",
    state: "NC",
    zip: 27616,
    month: "April",
    day: 17,
    year: 1974,
    position: "Corporate",
  },
  {
    id: "e5",
    name: "Kevin Malone",
    street: "876 St. Albans Dr",
    city: "Raleigh",
    state: "NC",
    zip: 27604,
    month: "May",
    day: 27,
    year: 1976,
    position: "Accounting",
  },
  {
    id: "e6",
    name: "Toby Flenderson",
    street: "956 Ralph Rd",
    city: "Raleigh",
    state: "NC",
    zip: 27609,
    month: "June",
    day: 6,
    year: 1977,
    position: "HR",
  },
  {
    id: "e7",
    name: "Stanley Hudson",
    street: "996 Pretty Ave",
    city: "Raleigh",
    state: "NC",
    zip: 27610,
    month: "July",
    day: 4,
    year: 1969,
    position: "Sales",
  },
  {
    id: "e8",
    name: "David Wallace",
    street: "432 St. Mary's St",
    city: "Raleigh",
    state: "NC",
    zip: 27603,
    month: "August",
    day: 19,
    year: 1965,
    position: "Corporate",
  },
  {
    id: "e9",
    name: "Angela Martin",
    street: "678 Way Back Ln",
    city: "Raleigh",
    state: "NC",
    zip: 27609,
    month: "September",
    day: 27,
    year: 1970,
    position: "Accounting",
  },
  {
    id: "e10",
    name: "Oscar Martinez",
    street: "996 Bob Ln",
    city: "Raleigh",
    state: "NC",
    zip: 27601,
    month: "October",
    day: 31,
    year: 1972,
    position: "Accounting",
  },
  {
    id: "e11",
    name: "Michael Scott",
    street: "1798 Dennis Ave",
    city: "Raleigh",
    state: "NC",
    zip: 27604,
    month: "November",
    day: 24,
    year: 1973,
    position: "Regional Manager",
  },
  {
    id: "e12",
    name: "Ryan Howard",
    street: "789 Wayberry St",
    city: "Raleigh",
    state: "NC",
    zip: 27615,
    month: "December",
    day: 5,
    year: 1986,
    position: "Temp",
  },
  {
    id: "e13",
    name: "Meredith Palmer",
    street: "334 Easy St",
    city: "Raleigh",
    state: "NC",
    zip: 27601,
    month: "January",
    day: 15,
    year: 1971,
    position: "Customer Service",
  },
  {
    id: "e14",
    name: "Darryl Philbin",
    street: "887 Rowdy Ln",
    city: "Raleigh",
    state: "NC",
    zip: 27607,
    month: "February",
    day: 16,
    year: 1979,
    position: "Warehouse",
  },
  {
    id: "e15",
    name: "Gabe Lewis",
    street: "7789 Gable Rd",
    city: "Raleigh",
    state: "NC",
    zip: 27605,
    month: "March",
    day: 3,
    year: 1982,
    position: "Corporate",
  },
  {
    id: "e16",
    name: "Kelly Kapoor",
    street: "9987 Harriet Rd",
    city: "Raleigh",
    state: "NC",
    zip: 27614,
    month: "April",
    day: "5",
    year: 1987,
    position: "Customer Relations",
  },
  {
    id: "e17",
    name: "Robert California",
    street: "6674 Lineberry Rd",
    city: "Raleigh",
    state: "NC",
    zip: 27603,
    month: "May",
    day: 8,
    year: 1964,
    position: "CEO",
  },
  {
    id: "e18",
    name: "Todd Packer",
    street: "6675 Hillsborough St",
    city: "Raleigh",
    state: "NC",
    zip: 27603,
    month: "June",
    day: 15,
    year: 1979,
    position: "Sales",
  },
  {
    id: "e19",
    name: "Erin Hannon",
    street: "456 Dennis Ave",
    city: "Raleigh",
    state: "NC",
    zip: 27604,
    month: "July",
    day: 4,
    year: 1987,
    position: "Reception",
  },
  {
    id: "e20",
    name: "Cathy Simms",
    street: "345 Lineberry Rd",
    city: "Raleigh",
    state: "NC",
    zip: 27603,
    month: "June",
    day: 25,
    year: 1989,
    position: "Intern",
  },
  {
    id: "e21",
    name: "Holly Flax",
    street: "7896 Midwood Dr",
    city: "Raleigh",
    state: "NC",
    zip: 27604,
    month: "November",
    day: 29,
    year: 1979,
    position: "HR",
  },
  {
    id: "e22",
    name: "Mose Schrute",
    street: "234 Beet Way",
    city: "Raleigh",
    state: "NC",
    zip: 27616,
    month: "December",
    day: 4,
    year: 1990,
    position: "Farm Hand",
  },
  {
    id: "e23",
    name: "Karen Filippelli",
    street: "7896 Stanley Rd",
    city: "Raleigh",
    state: "NC",
    zip: 27608,
    month: "August",
    day: 31,
    year: 1992,
    position: "Regional Manager",
  },
  {
    id: "e24",
    name: "Nellie Bertram",
    street: "234 Blount St.",
    city: "Raleigh",
    state: "NC",
    zip: 27602,
    month: "September",
    day: 8,
    year: 1979,
    position: "Special Events",
  },
  {
    id: "e25",
    name: "Pete Plop Miller",
    street: "234 Hargett St",
    city: "Raleigh",
    state: "NC",
    zip: 27603,
    month: "January",
    day: 29,
    year: 1987,
    position: "Public Relations",
  },
  {
    id: "e26",
    name: "Clark Green",
    street: "678 Ray Rd",
    city: "Raleigh",
    state: "NC",
    zip: 27608,
    month: "July",
    day: 17,
    year: 1984,
    position: "Sales",
  },
  {
    id: "e27",
    name: "Creed Bratton",
    street: "678 Creepy St",
    city: "Raleigh",
    state: "NC",
    zip: 27610,
    month: "October",
    day: 31,
    year: 1962,
    position: "Musician",
  },
  {
    id: "e28",
    name: "DeAngelo Vickers",
    street: "475 Blount St",
    city: "Raleigh",
    state: "NC",
    zip: 27605,
    month: "December",
    day: 1,
    year: 1969,
    position: "Regional Manager",
  },
  {
    id: "e29",
    name: "Phyllis Lapin-Vance",
    street: "345 Restful Pl",
    city: "Raleigh",
    state: "NC",
    zip: 27609,
    month: "July",
    day: 17,
    year: 1977,
    position: "Sales",
  },
  {
    id: "e30",
    name: "Bob Vance",
    street: "345 Restful Pl",
    city: "Raleigh",
    state: "NC",
    zip: 27609,
    month: "September",
    day: 15,
    year: 1978,
    position: "Vance Refrigeration",
  },
  {
    id: "e31",
    name: "Josh Porter",
    street: "9908 Romano St",
    city: "Raleigh",
    state: "NC",
    zip: 27608,
    month: "May",
    day: 19,
    year: 1983,
    position: "Regional Manager",
  },
  {
    id: "e32",
    name: "Hank Tate",
    street: "786 Brinderful Rd",
    city: "Raleigh",
    state: "NC",
    zip: 27610,
    month: "November",
    day: 7,
    year: 1970,
    position: "Security",
  },
  {
    id: "62b12a7d600c86e8af2263ee",
    name: "Kristin Thaxter",
    street: "7421 8th Lane",
    city: "Charlotte",
    state: "NC",
    zip: 28215,
    month: "August",
    day: 4,
    year: 1959,
    position: "Research Assistant IV",
  },
  {
    id: "62b12a7d600c86e8af2263ef",
    name: "Alexei McEllen",
    street: "50 Del Mar Parkway",
    city: "Raleigh",
    state: "NC",
    zip: 27626,
    month: "June",
    day: 21,
    year: 1991,
    position: "Help Desk Technician",
  },
  {
    id: "62b12a7d600c86e8af2263f0",
    name: "Silvanus Steere",
    street: "051 Mcbride Parkway",
    city: "Charlotte",
    state: "NC",
    zip: 28220,
    month: "February",
    day: 26,
    year: 1997,
    position: "VP Quality Control",
  },
  {
    id: "62b12a7d600c86e8af2263f1",
    name: "Courtnay Oylett",
    street: "4963 Linden Hill",
    city: "Winston Salem",
    state: "NC",
    zip: 27116,
    month: "May",
    day: 1,
    year: 1998,
    position: "Food Chemist",
  },
  {
    id: "62b12a7d600c86e8af2263f2",
    name: "Cleo Hurche",
    street: "258 Sommers Drive",
    city: "Charlotte",
    state: "NC",
    zip: 28225,
    month: "February",
    day: 19,
    year: 1989,
    position: "Mechanical Systems Engineer",
  },
  {
    id: "62b12a7d600c86e8af2263f3",
    name: "Mahala Cardno",
    street: "3 American Junction",
    city: "Fayetteville",
    state: "NC",
    zip: 28305,
    month: "January",
    day: 8,
    year: 1978,
    position: "Research Assistant III",
  },
  {
    id: "62b12a7d600c86e8af2263f4",
    name: "Julia Bidmead",
    street: "1630 Lakewood Plaza",
    city: "Raleigh",
    state: "NC",
    zip: 27658,
    month: "September",
    day: 10,
    year: 1991,
    position: "Developer IV",
  },
  {
    id: "62b12a7d600c86e8af2263f5",
    name: "Shawn Reason",
    street: "7088 Mcbride Circle",
    city: "Durham",
    state: "NC",
    zip: 27710,
    month: "September",
    day: 10,
    year: 1980,
    position: "Environmental Tech",
  },
  {
    id: "62b12a7d600c86e8af2263f6",
    name: "Oralia Pannett",
    street: "8598 Memorial Crossing",
    city: "Charlotte",
    state: "NC",
    zip: 28230,
    month: "September",
    day: 6,
    year: 1962,
    position: "Clinical Specialist",
  },
  {
    id: "62b12a7d600c86e8af2263f7",
    name: "Gifford Paaso",
    street: "96 Hallows Park",
    city: "Raleigh",
    state: "NC",
    zip: 27610,
    month: "April",
    day: 6,
    year: 1988,
    position: "Research Associate",
  },
  {
    id: "62b12a7d600c86e8af2263f8",
    name: "Elva Gregol",
    street: "09201 Drewry Center",
    city: "Greensboro",
    state: "NC",
    zip: 27409,
    month: "June",
    day: 8,
    year: 1977,
    position: "Librarian",
  },
  {
    id: "62b12a7d600c86e8af2263f9",
    name: "Clea Buckthought",
    street: "4 Straubel Pass",
    city: "Charlotte",
    state: "NC",
    zip: 28289,
    month: "November",
    day: 1,
    year: 1979,
    position: "Project Manager",
  },
  {
    id: "62b12a7d600c86e8af2263fa",
    name: "Doro Soares",
    street: "1929 Parkside Circle",
    city: "Charlotte",
    state: "NC",
    zip: 28210,
    month: "June",
    day: 12,
    year: 1963,
    position: "Food Chemist",
  },
  {
    id: "62b12a7d600c86e8af2263fb",
    name: "Emmett Bonifazio",
    street: "57686 Truax Point",
    city: "Charlotte",
    state: "NC",
    zip: 28256,
    month: "June",
    day: 11,
    year: 1993,
    position: "Budget",
  },
  {
    id: "62b12a7d600c86e8af2263fc",
    name: "Mead Lamlin",
    street: "4662 Alpine Point",
    city: "Charlotte",
    state: "NC",
    zip: 28263,
    month: "October",
    day: 21,
    year: 1983,
    position: "Senior Editor",
  },
  {
    id: "62b12a7d600c86e8af2263fd",
    name: "Aubrie Dimbylow",
    street: "80655 Del Sol Place",
    city: "Greensboro",
    state: "NC",
    zip: 27415,
    month: "October",
    day: 21,
    year: 1959,
    position: "Research Nurse",
  },
  {
    id: "62b12a7d600c86e8af2263fe",
    name: "Andrej Ruffell",
    street: "325 Schiller Trail",
    city: "Greensboro",
    state: "NC",
    zip: 27425,
    month: "December",
    day: 16,
    year: 1992,
    position: "Teacher",
  },
  {
    id: "62b12a7d600c86e8af2263ff",
    name: "Randolf Espinha",
    street: "01 Arkansas Trail",
    city: "Charlotte",
    state: "NC",
    zip: 28284,
    month: "February",
    day: 29,
    year: 1960,
    position: "Executive Secretary",
  },
  {
    id: "62b12a7d600c86e8af226400",
    name: "Margarette Croisdall",
    street: "009 Gateway Circle",
    city: "Raleigh",
    state: "NC",
    zip: 27615,
    month: "December",
    day: 12,
    year: 1967,
    position: "Assistant Media Planner",
  },
  {
    id: "62b12a7d600c86e8af226401",
    name: "Mollee Cunniff",
    street: "1371 6th Lane",
    city: "Charlotte",
    state: "NC",
    zip: 28289,
    month: "March",
    day: 1,
    year: 1955,
    position: "Senior Quality Engineer",
  },
];
const App = () => {
  const [employees, setEmployees] = useState(INITIAL_EMPLOYEES);

  const addEmployeeHandler = (employee) => {
    setEmployees((prevEmployees) => {
      return [employee, ...prevEmployees];
    });
    console.log("In App.js");
    console.log(employee);
  };
  return (
    <div>
      <NewEmployee onAddEmployee={addEmployeeHandler} />
      <DunderMifflinEmployees employees={employees} />
    </div>
  );
};

export default App;
