import React from "react";
import DunderMifflinEmployees from "./components/DunderMifflinEmployees";
import NewEmployee from "./components/NewEmployee/NewEmployee";
const App = () => {
  const employees = [
    {
      id: "e1",
      name: "Dwight Schrute",
      street: "234 Burt Ave",
      city: "Raleigh",
      state: "NC",
      zip: 27601,
      DOB_month: "January",
      DOB_day: 14,
      DOB_year: 1975,
      position: "Sales",
    },
    {
      id: "e2",
      name: "Jim Halpert",
      street: "234 Park Ave",
      city: "Raleigh",
      state: "NC",
      zip: 27604,
      DOB_month: "February",
      DOB_day: 25,
      DOB_year: 1978,
      position: "Sales",
    },
    {
      id: "e3",
      name: "Pam Beasley",
      street: "543 Lee St",
      city: "Raleigh",
      state: "NC",
      zip: 27609,
      DOB_month: "March",
      DOB_day: 5,
      DOB_year: 1985,
      position: "Reception",
    },
    {
      id: "e4",
      name: "Jan Levinson",
      street: "987 Easy St",
      city: "Raleigh",
      state: "NC",
      zip: 27616,
      DOB_month: "April",
      DOB_day: 17,
      DOB_year: 1974,
      position: "Corporate",
    },
    {
      id: "e5",
      name: "Kevin Malone",
      street: "876 St. Albans Dr",
      city: "Raleigh",
      state: "NC",
      zip: 27604,
      DOB_month: "May",
      DOB_day: 27,
      DOB_year: 1976,
      position: "Accounting",
    },
    {
      id: "e6",
      name: "Toby Flenderson",
      street: "956 Ralph Rd",
      city: "Raleigh",
      state: "NC",
      zip: 27609,
      DOB_month: "June",
      DOB_day: 6,
      DOB_year: 1977,
      position: "HR",
    },
    {
      id: "e7",
      name: "Stanley Hudson",
      street: "996 Pretty Ave",
      city: "Raleigh",
      state: "NC",
      zip: 27610,
      DOB_month: "July",
      DOB_day: 4,
      DOB_year: 1969,
      position: "Sales",
    },
    {
      id: "e8",
      name: "David Wallace",
      street: "432 St. Mary's St",
      city: "Raleigh",
      state: "NC",
      zip: 27603,
      DOB_month: "August",
      DOB_day: 19,
      DOB_year: 1965,
      position: "Corporate",
    },
    {
      id: "e9",
      name: "Angela Martin",
      street: "678 Way Back Ln",
      city: "Raleigh",
      state: "NC",
      zip: 27609,
      DOB_month: "September",
      DOB_day: 27,
      DOB_year: 1970,
      position: "Accounting",
    },
    {
      id: "e10",
      name: "Oscar Martinez",
      street: "996 Bob Ln",
      city: "Raleigh",
      state: "NC",
      zip: 27601,
      DOB_month: "October",
      DOB_day: 31,
      DOB_year: 1972,
      position: "Accounting",
    },
    {
      id: "e11",
      name: "Michael Scott",
      street: "1798 Dennis Ave",
      city: "Raleigh",
      state: "NC",
      zip: 27604,
      DOB_month: "November",
      DOB_day: 24,
      DOB_year: 1973,
      position: "Regional Manager",
    },
    {
      id: "e12",
      name: "Ryan Howard",
      street: "789 Wayberry St",
      city: "Raleigh",
      state: "NC",
      zip: 27615,
      DOB_month: "December",
      DOB_day: 5,
      DOB_year: 1986,
      position: "Temp",
    },
    {
      id: "e13",
      name: "Meredith Palmer",
      street: "334 Easy St",
      city: "Raleigh",
      state: "NC",
      zip: 27601,
      DOB_month: "January",
      DOB_day: 15,
      DOB_year: 1971,
      position: "Customer Service",
    },
    {
      id: "e14",
      name: "Darryl Philbin",
      street: "887 Rowdy Ln",
      city: "Raleigh",
      state: "NC",
      zip: 27607,
      DOB_month: "February",
      DOB_day: 16,
      DOB_year: 1979,
      position: "Warehouse",
    },
    {
      id: "e15",
      name: "Gabe Lewis",
      street: "7789 Gable Rd",
      city: "Raleigh",
      state: "NC",
      zip: 27605,
      DOB_month: "March",
      DOB_day: 3,
      DOB_year: 1982,
      position: "Corporate",
    },
    {
      id: "e16",
      name: "Kelly Kapoor",
      street: "9987 Harriet Rd",
      city: "Raleigh",
      state: "NC",
      zip: 27614,
      DOB_month: "April",
      DOB_day: "5",
      DOB_year: 1987,
      position: "Customer Relations",
    },
    {
      id: "e17",
      name: "Robert California",
      street: "6674 Lineberry Rd",
      city: "Raleigh",
      state: "NC",
      zip: 27603,
      DOB_month: "May",
      DOB_day: 8,
      DOB_year: 1964,
      position: "CEO",
    },
    {
      id: "e18",
      name: "Todd Packer",
      street: "6675 Hillsborough St",
      city: "Raleigh",
      state: "NC",
      zip: 27603,
      DOB_month: "June",
      DOB_day: 15,
      DOB_year: 1979,
      position: "Sales",
    },
  ];

  const addEmployeeHandler = (employee) => {
    console.log("In App.js");
    console.log(employee);
  };
  return (
    <div>
      <NewEmployee onAddEmployee={addEmployeeHandler} />
      <DunderMifflinEmployees employees={employees} />
    </div>
  );
};

export default App;
